// NOTE : [slug] makes it such that this page is loaded on any route that is not captured by the other routes specified in the 'pages' parent directory. We're intending for this file to specify the Profile view.
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const ProfilePage: NextPage = () => {
  const { data, isLoading } = api.profile.getUserByUsername.useQuery({
    username: "jjquek",
  });
  // TODO : implement getting username prop and understand why we use the SSG helper.
  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong...</div>;
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>{data.username}</div>
      </main>
    </>
  );
};

export default ProfilePage;
